services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=la@150903'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
