spring:
  application:
    name: sbdocs
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: la@150903
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      api-key: 
        options:
          model: gpt-4
  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimension: 1536
  docker:
    compose:
      lifecycle-management: start-only
    file: .aidocs/compose.yaml
#  main:
#    banner-mode: off
#logging:
#  level:
#    root: off